site: 小齐
url: https://johnwritejohn.vercel.app
title: 小齐
description: 我的写作
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: 小齐
  avatar:
  email: john.ren.contact@gmail.com
  url: https://johnwritejohn.vercel.app
permalink: pretty

timezone: Asia/Shanghai


baseurl: ""

highlighter: none

future: true

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 18

kramdown:
  hard_wrap: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year:month:day/:slug

defaults:
  - scope:
      path: "_posts/1944"
    values:
      type: "posts"
      layout: "post"
      tags: ["1944"]
  - scope:
      path: "_posts/诗"
    values:
      type: "posts"
      layout: "post"
      tags: [诗]
  - scope:
      path: "_posts"
    values:
      type: "posts"
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
