site: John's Blog
url:
baseurl: ""
title: John's Blog
description: 小齐的博客
author:
  name: 小齐
  avatar:
  email: john.ren.contact@gmail.com
permalink: pretty
timezone: Asia/Shanghai

future: true

exclude:
  - .jekyll-cache
  - update_blog.bat

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 18

kramdown:
  hard_wrap: true
  math_engine: katex

highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "_posts/bin"
    values:
      type: "posts"
      layout: "post"
      tags: ["折腾"]
  - scope:
      path: "_posts/thoughts"
    values:
      type: "posts"
      layout: "post"
      tags: ["想"]
  - scope:
      path: "_posts/bad"
    values:
      type: "posts"
      layout: "post"
      hidden: true
      tags: ["坏记录"]
  - scope:
      path: "_posts/**"
    values:
      type: "posts"
      layout: "post"
      tags: ["未归类"]
